{
	"mod":"modules/",
	"config":"config/",
	"data":"data/",
	"repo":"wendigo_test",
	"usr":"daniellohrey",
	"token":"ZWQ2YTVjZTQwYTU0NDM0MmNkMjJiZGI3MDUwN2MyMWRlMzIxNjBjMw==",
	"pk":"LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwVzBJRktuZWpiRWtROWt1OTMxeApLRHRJNVRncGJuK3htQ0RKcTZIOWlCOFZxZGJSdTZKUUE0ZjRrM0g3N09yU0ZxWm1EUDZDUkpCN0wwSzhBa2RnCmppaGVYR1RITmdaMkRxbmpvVHBvamM3VWVPMy9SdU5ZZnNXQUEzZWx5NmxkMmN3VDdaTStqNHk0NVVXS2o1aVgKeEZpYk9uVnVnMllhczQ3bEY2VXNjRXBpVXJSbnQyTlB6VFJxYkJneDk4ald5TUY1UGJZa2NtSXU4VkVBbE9FLwo4azEyREhkNndpTmtJSDNMYnN2cER1dDNDcHljMVVqTGhqMzJTRGZSWmpkV2R5K2ZPbmg5MEFTV1NQMlFKVGhQCmRhQXh4cng2ZzRMRkJjQWtWYjhYN1JmUGFOc1d2UUhZTGJtd1FPTzRvdXVrczcvV25MNnlXWW8yNGJqMUlpSzkKTHdJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t",
	"pwd":"password",
	"sleep":"10",
	"fn_s":"fn_mod",
	"id_s":"id_slp",
	"imp":"import %s",
	"size":"200"
}
